import 'dart:convert';
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() => runApp(const RudraSurveyorApp());

class RudraSurveyorApp extends StatelessWidget {
  const RudraSurveyorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'RUDRA SURVEYOR',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1565C0)),
        scaffoldBackgroundColor: const Color(0xFFF5F7FB),
      ),
      home: const Dashboard(),
    );
  }
}

class HistoryStore {
  static const recordsKey = 'land_records';
  static const filesKey = 'saved_files';

  static Future<List<Map<String, dynamic>>> records() async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(recordsKey) ?? [];
    return list.map<Map<String, dynamic>>((e) {
      try {
        return Map<String, dynamic>.from(jsonDecode(e) as Map);
      } catch (_) {
        return <String, dynamic>{};
      }
    }).where((e) => e.isNotEmpty).toList();
  }

  static Future<void> addRecord(Map<String, dynamic> record) async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(recordsKey) ?? [];
    list.add(jsonEncode(record));
    await p.setStringList(recordsKey, list);
  }

  static Future<void> deleteRecord(int index) async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(recordsKey) ?? [];
    if (index >= 0 && index < list.length) {
      list.removeAt(index);
      await p.setStringList(recordsKey, list);
    }
  }

  static Future<void> addFile(Map<String, dynamic> file) async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(filesKey) ?? [];
    list.add(jsonEncode(file));
    await p.setStringList(filesKey, list);
  }

  static Future<List<Map<String, dynamic>>> files() async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(filesKey) ?? [];
    return list.map<Map<String, dynamic>>((e) {
      try {
        return Map<String, dynamic>.from(jsonDecode(e) as Map);
      } catch (_) {
        return <String, dynamic>{};
      }
    }).where((e) => e.isNotEmpty).toList();
  }

  static Future<void> deleteFile(int index) async {
    final p = await SharedPreferences.getInstance();
    final list = p.getStringList(filesKey) ?? [];
    if (index >= 0 && index < list.length) {
      final item = jsonDecode(list[index]);
      final path = item is Map ? item['path']?.toString() : null;
      if (path != null) {
        try {
          final f = File(path);
          if (await f.exists()) await f.delete();
        } catch (_) {}
      }
      list.removeAt(index);
      await p.setStringList(filesKey, list);
    }
  }
}

class PdfService {
  static Future<File> createReport(Map<String, dynamic> r) async {
    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (_) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Center(
              child: pw.Text('RUDRA SURVEYOR', style: pw.TextStyle(fontSize: 25, fontWeight: pw.FontWeight.bold)),
            ),
            pw.SizedBox(height: 5),
            pw.Center(child: pw.Text('LAND SURVEY REPORT', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold))),
            pw.SizedBox(height: 18),
            pw.Divider(),
            _row('Owner Name', r['owner']),
            _row('Mobile Number', r['mobile']),
            _row('Village', r['village']),
            _row('Taluka', r['taluka']),
            _row('Survey Number', r['survey']),
            _row('Survey Date', r['date']),
            _row('Total Payment', 'Rs. ${r['payment'] ?? '0'}'),
            if ((r['fileName'] ?? '').toString().isNotEmpty) _row('Uploaded File', r['fileName']),
            pw.SizedBox(height: 25),
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey)),
              child: pw.Text('This report is generated by RUDRA SURVEYOR application.', style: const pw.TextStyle(fontSize: 10)),
            ),
            pw.Spacer(),
            pw.Center(child: pw.Text('RUDRA SURVEYOR', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
          ],
        ),
      ),
    );
    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/RUDRA_SURVEY_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await doc.save());
    return file;
  }

  static pw.Widget _row(String title, dynamic value) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 10),
        child: pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.SizedBox(width: 145, child: pw.Text(title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
            pw.Expanded(child: pw.Text(value?.toString() ?? '-')),
          ],
        ),
      );

  static Future<void> preview(Map<String, dynamic> r) async {
    final file = await createReport(r);
    final bytes = await file.readAsBytes();
    await Printing.layoutPdf(onLayout: (_) async => bytes);
  }

  static Future<void> share(Map<String, dynamic> r) async {
    final file = await createReport(r);
    await Share.shareXFiles([XFile(file.path)], text: 'RUDRA SURVEYOR Report');
  }
}

class Dashboard extends StatefulWidget {
  const Dashboard({super.key});
  @override
  State<Dashboard> createState() => _DashboardState();
}

class _DashboardState extends State<Dashboard> {
  int tab = 0;

  void open(Widget page) => Navigator.push(context, MaterialPageRoute(builder: (_) => page));

  @override
  Widget build(BuildContext context) {
    final pages = [
      _home(),
      HistoryPage(onHome: () => setState(() => tab = 0)),
      const GpsPage(),
      const ProfilePage(),
    ];
    return Scaffold(
      body: SafeArea(child: pages[tab]),
      bottomNavigationBar: NavigationBar(
        selectedIndex: tab,
        onDestinationSelected: (i) => setState(() => tab = i),
        destinations: const [
          NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home), label: 'Home'),
          NavigationDestination(icon: Icon(Icons.history), label: 'History'),
          NavigationDestination(icon: Icon(Icons.location_on_outlined), selectedIcon: Icon(Icons.location_on), label: 'Map'),
          NavigationDestination(icon: Icon(Icons.person_outline), selectedIcon: Icon(Icons.person), label: 'Profile'),
        ],
      ),
    );
  }

  Widget _home() {
    return FutureBuilder<List<Map<String, dynamic>>>(
      future: HistoryStore.records(),
      builder: (context, snap) {
        final records = snap.data ?? [];
        final payment = records.fold<double>(0, (sum, r) => sum + (double.tryParse('${r['payment'] ?? 0}') ?? 0));
        return ListView(
          padding: const EdgeInsets.fromLTRB(16, 16, 16, 24),
          children: [
            _header(),
            const SizedBox(height: 18),
            _welcomeCard(),
            const SizedBox(height: 18),
            const Text('Operations', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 12),
            _opCard('OP1', 'Land Entry', 'Owner, land and payment details', Icons.edit_document, const Color(0xFF1565C0), () => open(const LandEntryPage())),
            _opCard('OP2', 'GPS Survey', 'GPS survey tools', Icons.gps_fixed, const Color(0xFF00897B), () => open(const GpsPage())),
            _opCard('OP3', 'Unit Conversion', 'Length and land-area units', Icons.swap_horiz, const Color(0xFF7B1FA2), () => open(const UnitPage())),
            _opCard('OP4', 'Area Calculator', 'Length × Width = m²', Icons.calculate, const Color(0xFFEF6C00), () => open(const AreaPage())),
            const SizedBox(height: 12),
            Card(
              child: ListTile(
                leading: const CircleAvatar(child: Icon(Icons.folder)),
                title: const Text('Saved Files', style: TextStyle(fontWeight: FontWeight.bold)),
                subtitle: const Text('Browse uploaded files saved inside the app'),
                trailing: const Icon(Icons.chevron_right),
                onTap: () => open(const SavedFilesPage()),
              ),
            ),
            const SizedBox(height: 12),
            Card(
              child: Padding(
                padding: const EdgeInsets.all(18),
                child: Row(
                  children: [
                    const Icon(Icons.history, size: 35, color: Color(0xFF1565C0)),
                    const SizedBox(width: 14),
                    Expanded(child: Text('${records.length} Saved Records', style: const TextStyle(fontSize: 17, fontWeight: FontWeight.bold))),
                    Text('₹${payment.toStringAsFixed(0)}', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                  ],
                ),
              ),
            ),
          ],
        );
      },
    );
  }

  Widget _header() => Row(
        children: [
          ClipRRect(borderRadius: BorderRadius.circular(14), child: Image.asset('assets/rudra_logo.jpg', width: 58, height: 58, fit: BoxFit.cover)),
          const SizedBox(width: 12),
          const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('RUDRA SURVEYOR', style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold)), Text('Professional Land Survey Tools')]))
        ],
      );

  Widget _welcomeCard() => Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(borderRadius: BorderRadius.circular(22), gradient: const LinearGradient(colors: [Color(0xFF1565C0), Color(0xFF42A5F5)])),
        child: const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('RUDRA SURVEYOR', style: TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold)), SizedBox(height: 6), Text('Fast • Simple • Professional', style: TextStyle(color: Colors.white70, fontSize: 15))]),
      );

  Widget _opCard(String no, String title, String sub, IconData icon, Color color, VoidCallback onTap) => Card(
        margin: const EdgeInsets.only(bottom: 10),
        child: ListTile(
          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 7),
          leading: CircleAvatar(backgroundColor: color.withOpacity(.12), foregroundColor: color, child: Icon(icon)),
          title: Text('$no • $title', style: const TextStyle(fontWeight: FontWeight.bold)),
          subtitle: Text(sub),
          trailing: const Icon(Icons.chevron_right),
          onTap: onTap,
        ),
      );
}

class LandEntryPage extends StatefulWidget {
  const LandEntryPage({super.key});
  @override
  State<LandEntryPage> createState() => _LandEntryPageState();
}

class _LandEntryPageState extends State<LandEntryPage> {
  final owner = TextEditingController();
  final mobile = TextEditingController();
  final village = TextEditingController();
  final taluka = TextEditingController();
  final survey = TextEditingController();
  final payment = TextEditingController();
  DateTime date = DateTime.now();
  File? selectedFile;
  String? selectedFileName;
  bool saving = false;

  @override
  void dispose() {
    owner.dispose(); mobile.dispose(); village.dispose(); taluka.dispose(); survey.dispose(); payment.dispose();
    super.dispose();
  }

  Future<void> chooseDate() async {
    final d = await showDatePicker(context: context, initialDate: date, firstDate: DateTime(2000), lastDate: DateTime(2100));
    if (d != null) setState(() => date = d);
  }

  Future<void> pickFile() async {
    final result = await FilePicker.platform.pickFiles(withData: false, allowMultiple: false);
    if (result == null || result.files.single.path == null) return;
    final picked = File(result.files.single.path!);
    final dir = await getApplicationDocumentsDirectory();
    final saveDir = Directory('${dir.path}/SavedFiles');
    if (!await saveDir.exists()) await saveDir.create(recursive: true);
    final safeName = '${DateTime.now().millisecondsSinceEpoch}_${result.files.single.name.replaceAll(RegExp(r'[\\/:*?"<>|]'), '_')}';
    final saved = await picked.copy('${saveDir.path}/$safeName');
    setState(() {
      selectedFile = saved;
      selectedFileName = result.files.single.name;
    });
  }

  Future<void> save() async {
    if (owner.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('માલિકનું નામ દાખલ કરો')));
      return;
    }
    setState(() => saving = true);
    try {
      String? savedPath;
      if (selectedFile != null) {
        savedPath = selectedFile!.path;
        await HistoryStore.addFile({'name': selectedFileName ?? selectedFile!.uri.pathSegments.last, 'path': savedPath, 'date': DateTime.now().toIso8601String()});
      }
      final record = {
        'owner': owner.text.trim(),
        'mobile': mobile.text.trim(),
        'village': village.text.trim(),
        'taluka': taluka.text.trim(),
        'survey': survey.text.trim(),
        'date': '${date.day}/${date.month}/${date.year}',
        'payment': payment.text.trim(),
        'fileName': selectedFileName ?? '',
        'filePath': savedPath ?? '',
      };
      await HistoryStore.addRecord(record);
      final pdf = await PdfService.createReport(record);
      if (!mounted) return;
      await showDialog<void>(
        context: context,
        builder: (_) => AlertDialog(
          title: const Text('Saved Successfully'),
          content: Text(selectedFileName == null ? 'Record saved. PDF report is ready.' : 'Record and file saved. PDF report is ready.'),
          actions: [
            TextButton(onPressed: () { Navigator.pop(context); Printing.layoutPdf(onLayout: (_) async => pdf.readAsBytes()); }, child: const Text('Preview PDF')),
            TextButton(onPressed: () { Navigator.pop(context); Share.shareXFiles([XFile(pdf.path)], text: 'RUDRA SURVEYOR Report'); }, child: const Text('Share')),
            FilledButton(onPressed: () => Navigator.pop(context), child: const Text('Done')),
          ],
        ),
      );
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Save error: $e')));
    } finally {
      if (mounted) setState(() => saving = false);
    }
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('OP1 • Land Entry')),
        body: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            AppField(controller: owner, label: 'માલિકનું નામ', icon: Icons.person),
            AppField(controller: mobile, label: 'મોબાઇલ નંબર', icon: Icons.phone, keyboard: TextInputType.phone),
            AppField(controller: village, label: 'ગામ', icon: Icons.location_city),
            AppField(controller: taluka, label: 'તાલુકો', icon: Icons.location_on),
            AppField(controller: survey, label: 'સર્વે નંબર', icon: Icons.numbers),
            InkWell(
              onTap: chooseDate,
              child: InputDecorator(decoration: const InputDecoration(labelText: 'માપણીની તારીખ', prefixIcon: Icon(Icons.calendar_month), border: OutlineInputBorder()), child: Text('${date.day}/${date.month}/${date.year}')),
            ),
            const SizedBox(height: 14),
            AppField(controller: payment, label: 'કુલ પેમેન્ટ (₹)', icon: Icons.currency_rupee, keyboard: const TextInputType.numberWithOptions(decimal: true)),
            const SizedBox(height: 14),
            OutlinedButton.icon(onPressed: pickFile, icon: const Icon(Icons.upload_file), label: Text(selectedFileName == null ? 'Upload a File' : 'Selected: $selectedFileName')),
            if (selectedFileName != null) ...[
              const SizedBox(height: 8),
              Text('File will be saved inside the app.', style: TextStyle(color: Colors.grey.shade700)),
            ],
            const SizedBox(height: 20),
            SizedBox(height: 54, child: FilledButton.icon(onPressed: saving ? null : save, icon: saving ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : const Icon(Icons.save), label: Text(saving ? 'Saving...' : 'Save + PDF Report'))),
          ],
        ),
      );
}

class HistoryPage extends StatefulWidget {
  final VoidCallback onHome;
  const HistoryPage({super.key, required this.onHome});
  @override
  State<HistoryPage> createState() => _HistoryPageState();
}

class _HistoryPageState extends State<HistoryPage> {
  List<Map<String, dynamic>> records = [];
  @override
  void initState() { super.initState(); load(); }
  Future<void> load() async { final r = await HistoryStore.records(); if (mounted) setState(() => records = r.reversed.toList()); }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('Saved History')),
        body: records.isEmpty
            ? const Center(child: Text('No saved records'))
            : ListView.builder(
                padding: const EdgeInsets.all(12),
                itemCount: records.length,
                itemBuilder: (_, i) {
                  final r = records[i];
                  return Card(
                    child: Padding(
                      padding: const EdgeInsets.all(14),
                      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                        Text(r['owner']?.toString() ?? '-', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                        Text('Survey: ${r['survey'] ?? '-'}  •  ${r['date'] ?? '-'}'),
                        Text('Village: ${r['village'] ?? '-'}  •  Taluka: ${r['taluka'] ?? '-'}'),
                        Text('Payment: ₹${r['payment'] ?? '0'}'),
                        if ((r['fileName'] ?? '').toString().isNotEmpty) Text('File: ${r['fileName']}'),
                        const SizedBox(height: 8),
                        Wrap(spacing: 8, children: [
                          OutlinedButton.icon(onPressed: () => PdfService.preview(r), icon: const Icon(Icons.picture_as_pdf), label: const Text('PDF')),
                          OutlinedButton.icon(onPressed: () => PdfService.share(r), icon: const Icon(Icons.share), label: const Text('Share')),
                          IconButton(onPressed: () async { await HistoryStore.deleteRecord(records.length - 1 - i); await load(); }, icon: const Icon(Icons.delete_outline)),
                        ]),
                      ]),
                    ),
                  );
                },
              ),
      );
}

class SavedFilesPage extends StatefulWidget {
  const SavedFilesPage({super.key});
  @override
  State<SavedFilesPage> createState() => _SavedFilesPageState();
}

class _SavedFilesPageState extends State<SavedFilesPage> {
  List<Map<String, dynamic>> files = [];
  @override
  void initState() { super.initState(); load(); }
  Future<void> load() async { final f = await HistoryStore.files(); if (mounted) setState(() => files = f.reversed.toList()); }

  Future<void> shareFile(Map<String, dynamic> item) async {
    final path = item['path']?.toString();
    if (path == null) return;
    final f = File(path);
    if (await f.exists()) await Share.shareXFiles([XFile(path)], text: item['name']?.toString() ?? 'RUDRA SURVEYOR file');
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('Saved Files')),
        body: files.isEmpty
            ? const Center(child: Text('No uploaded files saved yet'))
            : ListView.builder(
                itemCount: files.length,
                padding: const EdgeInsets.all(12),
                itemBuilder: (_, i) {
                  final f = files[i];
                  return Card(
                    child: ListTile(
                      leading: const CircleAvatar(child: Icon(Icons.insert_drive_file)),
                      title: Text(f['name']?.toString() ?? 'File'),
                      subtitle: Text(f['date']?.toString().split('T').first ?? ''),
                      trailing: Wrap(children: [
                        IconButton(onPressed: () => shareFile(f), icon: const Icon(Icons.share)),
                        IconButton(onPressed: () async { await HistoryStore.deleteFile(files.length - 1 - i); await load(); }, icon: const Icon(Icons.delete_outline)),
                      ]),
                    ),
                  );
                },
              ),
      );
}

class AreaPage extends StatefulWidget {
  const AreaPage({super.key});
  @override
  State<AreaPage> createState() => _AreaPageState();
}

class _AreaPageState extends State<AreaPage> {
  final length = TextEditingController();
  final width = TextEditingController();
  double area = 0;
  void calculate() => setState(() => area = (double.tryParse(length.text) ?? 0) * (double.tryParse(width.text) ?? 0));
  @override
  void dispose() { length.dispose(); width.dispose(); super.dispose(); }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('OP4 • Area Calculator')),
        body: ListView(padding: const EdgeInsets.all(16), children: [
          AppField(controller: length, label: 'લંબાઈ (મીટર)', icon: Icons.straighten, keyboard: const TextInputType.numberWithOptions(decimal: true)),
          AppField(controller: width, label: 'પહોળાઈ (મીટર)', icon: Icons.straighten, keyboard: const TextInputType.numberWithOptions(decimal: true)),
          const SizedBox(height: 10),
          FilledButton(onPressed: calculate, child: const Text('Calculate Area')),
          const SizedBox(height: 25),
          Center(child: Text('${area.toStringAsFixed(2)} m²', style: const TextStyle(fontSize: 32, fontWeight: FontWeight.bold))),
        ]),
      );
}

class UnitPage extends StatefulWidget {
  const UnitPage({super.key});
  @override
  State<UnitPage> createState() => _UnitPageState();
}

class _UnitPageState extends State<UnitPage> {
  final input = TextEditingController();
  String from = 'Meter';
  String to = 'Feet';
  String result = '0';

  final units = const ['Meter', 'Feet', 'Inch', 'Yard', 'm²', 'ft²', 'yd²', 'Acre', 'Hectare', 'Guntha'];
  final areaUnits = const {'m²', 'ft²', 'yd²', 'Acre', 'Hectare', 'Guntha'};

  double toBase(double v, String unit) {
    switch (unit) {
      case 'Feet': return v * 0.3048;
      case 'Inch': return v * 0.0254;
      case 'Yard': return v * 0.9144;
      case 'ft²': return v * 0.09290304;
      case 'yd²': return v * 0.83612736;
      case 'Acre': return v * 4046.8564224;
      case 'Hectare': return v * 10000;
      case 'Guntha': return v * 101.17141056;
      default: return v;
    }
  }

  double fromBase(double v, String unit) {
    switch (unit) {
      case 'Feet': return v / 0.3048;
      case 'Inch': return v / 0.0254;
      case 'Yard': return v / 0.9144;
      case 'ft²': return v / 0.09290304;
      case 'yd²': return v / 0.83612736;
      case 'Acre': return v / 4046.8564224;
      case 'Hectare': return v / 10000;
      case 'Guntha': return v / 101.17141056;
      default: return v;
    }
  }

  void convert() {
    final v = double.tryParse(input.text) ?? 0;
    final bothArea = areaUnits.contains(from) && areaUnits.contains(to);
    final bothLength = !areaUnits.contains(from) && !areaUnits.contains(to);
    if (!bothArea && !bothLength) {
      setState(() => result = 'Length અને Area units mix કરી શકાતા નથી');
      return;
    }
    setState(() => result = fromBase(toBase(v, from), to).toStringAsFixed(4));
  }

  @override
  void dispose() { input.dispose(); super.dispose(); }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('OP3 • Unit Conversion')),
        body: ListView(padding: const EdgeInsets.all(16), children: [
          AppField(controller: input, label: 'Value', icon: Icons.numbers, keyboard: const TextInputType.numberWithOptions(decimal: true)),
          DropdownButtonFormField<String>(value: from, decoration: const InputDecoration(labelText: 'From', border: OutlineInputBorder()), items: units.map((u) => DropdownMenuItem(value: u, child: Text(u))).toList(), onChanged: (v) { if (v != null) setState(() => from = v); }),
          const SizedBox(height: 12),
          DropdownButtonFormField<String>(value: to, decoration: const InputDecoration(labelText: 'To', border: OutlineInputBorder()), items: units.map((u) => DropdownMenuItem(value: u, child: Text(u))).toList(), onChanged: (v) { if (v != null) setState(() => to = v); }),
          const SizedBox(height: 15),
          FilledButton(onPressed: convert, child: const Text('Convert')),
          const SizedBox(height: 20),
          Center(child: Text('$result $to', style: const TextStyle(fontSize: 26, fontWeight: FontWeight.bold))),
        ]),
      );
}

class GpsPage extends StatelessWidget {
  const GpsPage({super.key});
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('OP2 • GPS Survey')),
        body: const Center(child: Padding(padding: EdgeInsets.all(25), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Icon(Icons.gps_fixed, size: 80, color: Color(0xFF00897B)), SizedBox(height: 15), Text('GPS Survey', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)), SizedBox(height: 8), Text('GPS tools can be connected here when location functionality is added.', textAlign: TextAlign.center)]))),
      );
}

class ProfilePage extends StatelessWidget {
  const ProfilePage({super.key});
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('Profile')),
        body: ListView(padding: const EdgeInsets.all(20), children: const [
          CircleAvatar(radius: 48, child: Icon(Icons.person, size: 55)),
          SizedBox(height: 16),
          Center(child: Text('RUDRA SURVEYOR', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold))),
          SizedBox(height: 8),
          Center(child: Text('Professional Land Survey Tools')),
        ]),
      );
}

class AppField extends StatelessWidget {
  final TextEditingController controller;
  final String label;
  final IconData icon;
  final TextInputType? keyboard;
  const AppField({super.key, required this.controller, required this.label, required this.icon, this.keyboard});
  @override
  Widget build(BuildContext context) => Padding(
        padding: const EdgeInsets.only(bottom: 14),
        child: TextField(controller: controller, keyboardType: keyboard, decoration: InputDecoration(labelText: label, prefixIcon: Icon(icon), border: const OutlineInputBorder())),
      );
}
