import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(const RudraSurveyorApp());
}

// ============================================================
// APP
// ============================================================

class RudraSurveyorApp extends StatelessWidget {
  const RudraSurveyorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'RUDRA SURVEYOR',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1565C0),
        ),
        scaffoldBackgroundColor: const Color(0xFFF5F7FB),
      ),
      home: const Dashboard(),
    );
  }
}

// ============================================================
// STORAGE
// ============================================================

class HistoryStore {
  static const String key = 'land_records';

  static Future<List<Map<String, dynamic>>> getRecords() async {
    final prefs = await SharedPreferences.getInstance();
    final list = prefs.getStringList(key) ?? [];

    return list.map((e) {
      return Map<String, dynamic>.from(jsonDecode(e));
    }).toList();
  }

  static Future<void> addRecord(
    Map<String, dynamic> record,
  ) async {
    final prefs = await SharedPreferences.getInstance();
    final list = prefs.getStringList(key) ?? [];

    list.add(jsonEncode(record));
    await prefs.setStringList(key, list);
  }

  static Future<void> deleteRecord(int index) async {
    final prefs = await SharedPreferences.getInstance();
    final list = prefs.getStringList(key) ?? [];

    if (index >= 0 && index < list.length) {
      list.removeAt(index);
      await prefs.setStringList(key, list);
    }
  }
}

// ============================================================
// PDF SERVICE
// ============================================================

class PdfService {
  static Future<File> createPdf(
    Map<String, dynamic> record,
  ) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(30),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [

              pw.Center(
                child: pw.Text(
                  'RUDRA SURVEYOR',
                  style: pw.TextStyle(
                    fontSize: 26,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),

              pw.SizedBox(height: 5),

              pw.Center(
                child: pw.Text(
                  'LAND SURVEY MEASUREMENT REPORT',
                  style: pw.TextStyle(
                    fontSize: 13,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),

              pw.SizedBox(height: 20),

              pw.Divider(),

              pw.SizedBox(height: 15),

              _pdfRow(
                'Owner Name',
                record['owner'] ?? '-',
              ),

              _pdfRow(
                'Mobile Number',
                record['mobile'] ?? '-',
              ),

              _pdfRow(
                'Village',
                record['village'] ?? '-',
              ),

              _pdfRow(
                'Taluka',
                record['taluka'] ?? '-',
              ),

              _pdfRow(
                'Survey Number',
                record['survey'] ?? '-',
              ),

              _pdfRow(
                'Survey Date',
                record['date'] ?? '-',
              ),

              pw.SizedBox(height: 10),

              pw.Divider(),

              pw.SizedBox(height: 10),

              _pdfRow(
                'Length',
                '${record['length'] ?? '0'} Meter',
              ),

              _pdfRow(
                'Width',
                '${record['width'] ?? '0'} Meter',
              ),

              _pdfRow(
                'Total Area',
                '${record['area'] ?? '0'} Square Meter',
              ),

              _pdfRow(
                'Total Payment',
                'Rs. ${record['payment'] ?? '0'}',
              ),

              pw.SizedBox(height: 30),

              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(
                    color: PdfColors.grey,
                  ),
                ),
                child: pw.Text(
                  'This report is generated by RUDRA SURVEYOR application.',
                  style: const pw.TextStyle(
                    fontSize: 10,
                  ),
                ),
              ),

              pw.Spacer(),

              pw.Center(
                child: pw.Text(
                  'RUDRA SURVEYOR',
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );

    final directory =
        await getApplicationDocumentsDirectory();

    final fileName =
        'RUDRA_SURVEY_${DateTime.now().millisecondsSinceEpoch}.pdf';

    final file = File(
      '${directory.path}/$fileName',
    );

    await file.writeAsBytes(
      await pdf.save(),
    );

    return file;
  }

  static pw.Widget _pdfRow(
    String title,
    String value,
  ) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Row(
        crossAxisAlignment:
            pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 150,
            child: pw.Text(
              title,
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value),
          ),
        ],
      ),
    );
  }

  static Future<void> previewPdf(
    Map<String, dynamic> record,
  ) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(30),
        build: (context) {
          return pw.Column(
            crossAxisAlignment:
                pw.CrossAxisAlignment.start,
            children: [

              pw.Center(
                child: pw.Text(
                  'RUDRA SURVEYOR',
                  style: pw.TextStyle(
                    fontSize: 26,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),

              pw.SizedBox(height: 5),

              pw.Center(
                child: pw.Text(
                  'LAND SURVEY MEASUREMENT REPORT',
                  style: pw.TextStyle(
                    fontSize: 13,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),

              pw.SizedBox(height: 20),

              pw.Divider(),

              pw.SizedBox(height: 15),

              PdfService._pdfRow(
                'Owner Name',
                record['owner'] ?? '-',
              ),

              PdfService._pdfRow(
                'Mobile Number',
                record['mobile'] ?? '-',
              ),

              PdfService._pdfRow(
                'Village',
                record['village'] ?? '-',
              ),

              PdfService._pdfRow(
                'Taluka',
                record['taluka'] ?? '-',
              ),

              PdfService._pdfRow(
                'Survey Number',
                record['survey'] ?? '-',
              ),

              PdfService._pdfRow(
                'Date',
                record['date'] ?? '-',
              ),

              pw.SizedBox(height: 10),

              pw.Divider(),

              pw.SizedBox(height: 10),

              PdfService._pdfRow(
                'Length',
                '${record['length'] ?? '0'} Meter',
              ),

              PdfService._pdfRow(
                'Width',
                '${record['width'] ?? '0'} Meter',
              ),

              PdfService._pdfRow(
                'Total Area',
                '${record['area'] ?? '0'} Square Meter',
              ),

              PdfService._pdfRow(
                'Payment',
                'Rs. ${record['payment'] ?? '0'}',
              ),

              pw.Spacer(),

              pw.Center(
                child: pw.Text(
                  'Generated by RUDRA SURVEYOR',
                ),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async {
        return pdf.save();
      },
    );
  }

  static Future<void> sharePdf(
    Map<String, dynamic> record,
  ) async {
    final file = await createPdf(record);

    await Share.shareXFiles(
      [
        XFile(
          file.path,
          mimeType: 'application/pdf',
        ),
      ],
      subject: 'RUDRA SURVEYOR Land Survey Report',
      text: 'Land Survey Report - RUDRA SURVEYOR',
    );
  }
}

// ============================================================
// DASHBOARD
// ============================================================

class Dashboard extends StatefulWidget {
  const Dashboard({super.key});

  @override
  State<Dashboard> createState() =>
      _DashboardState();
}

class _DashboardState extends State<Dashboard> {
  int currentIndex = 0;

  int totalRecords = 0;
  double totalPayment = 0;

  @override
  void initState() {
    super.initState();
    loadStats();
  }

  Future<void> loadStats() async {
    final records =
        await HistoryStore.getRecords();

    double payment = 0;

    for (final r in records) {
      payment +=
          double.tryParse(
                r['payment']?.toString() ?? '0',
              ) ??
              0;
    }

    if (!mounted) return;

    setState(() {
      totalRecords = records.length;
      totalPayment = payment;
    });
  }

  Future<void> openPage(Widget page) async {
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => page,
      ),
    );

    loadStats();
  }

  @override
  Widget build(BuildContext context) {
    if (currentIndex == 1) {
      return HistoryPage(
        onHome: () {
          setState(() {
            currentIndex = 0;
          });
        },
      );
    }

    if (currentIndex == 2) {
      return MapPage(
        onHome: () {
          setState(() {
            currentIndex = 0;
          });
        },
      );
    }

    if (currentIndex == 3) {
      return ProfilePage(
        onHome: () {
          setState(() {
            currentIndex = 0;
          });
        },
      );
    }

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        title: const Text(
          'RUDRA SURVEYOR',
          style: TextStyle(
            fontWeight: FontWeight.bold,
            color: Color(0xFF123B68),
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(
              Icons.settings_outlined,
            ),
            onPressed: () {
              openPage(
                const SettingsPage(),
              );
            },
          ),
        ],
      ),

      body: RefreshIndicator(
        onRefresh: loadStats,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [

            // HEADER
            Container(
              padding: const EdgeInsets.all(18),
              decoration: BoxDecoration(
                borderRadius:
                    BorderRadius.circular(24),
                gradient:
                    const LinearGradient(
                  colors: [
                    Color(0xFF1565C0),
                    Color(0xFF42A5F5),
                  ],
                ),
              ),
              child: Row(
                children: [

                  Container(
                    width: 70,
                    height: 70,
                    padding:
                        const EdgeInsets.all(6),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius:
                          BorderRadius.circular(18),
                    ),
                    child: Image.asset(
                      'assets/rudra_logo.jpg',
                      fit: BoxFit.contain,
                    ),
                  ),

                  const SizedBox(width: 15),

                  const Expanded(
                    child: Column(
                      crossAxisAlignment:
                          CrossAxisAlignment.start,
                      children: [
                        Text(
                          'નમસ્તે! 👋',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontWeight:
                                FontWeight.bold,
                          ),
                        ),
                        SizedBox(height: 5),
                        Text(
                          'RUDRA SURVEYOR માં આપનું સ્વાગત છે.',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 13,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 22),

            const Text(
              'Survey Operations',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Color(0xFF173A5E),
              ),
            ),

            const SizedBox(height: 12),

            OperationCard(
              number: 'OP1',
              title: 'જમીન માપણી નોંધ',
              description:
                  'માલિક, ગામ, તાલુકો, સર્વે નંબર, માપણી અને પેમેન્ટ નોંધો.',
              icon: Icons.edit_document,
              colors: const [
                Color(0xFF1565C0),
                Color(0xFF42A5F5),
              ],
              onTap: () {
                openPage(
                  const LandEntryPage(),
                );
              },
            ),

            const SizedBox(height: 12),

            OperationCard(
              number: 'OP2',
              title: 'GPS Survey',
              description:
                  'GPS દ્વારા સ્થાન અને survey સંબંધિત માહિતી.',
              icon: Icons.gps_fixed,
              colors: const [
                Color(0xFF00897B),
                Color(0xFF26A69A),
              ],
              onTap: () {
                openPage(
                  const GpsPage(),
                );
              },
            ),

            const SizedBox(height: 12),

            OperationCard(
              number: 'OP3',
              title: 'Unit Conversion',
              description:
                  'Meter, Feet, Inch અને Yard convert કરો.',
              icon: Icons.swap_horiz,
              colors: const [
                Color(0xFF7B1FA2),
                Color(0xFFAB47BC),
              ],
              onTap: () {
                openPage(
                  const UnitPage(),
                );
              },
            ),

            const SizedBox(height: 12),

            OperationCard(
              number: 'OP4',
              title: 'Area Calculator',
              description:
                  'લંબાઈ અને પહોળાઈ પરથી area ગણો.',
              icon: Icons.calculate,
              colors: const [
                Color(0xFFEF6C00),
                Color(0xFFFFA726),
              ],
              onTap: () {
                openPage(
                  const AreaPage(),
                );
              },
            ),

            const SizedBox(height: 24),

            const Text(
              'Saved History',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Color(0xFF173A5E),
              ),
            ),

            const SizedBox(height: 12),

            InkWell(
              borderRadius:
                  BorderRadius.circular(22),
              onTap: () {
                setState(() {
                  currentIndex = 1;
                });
              },
              child: Container(
                padding:
                    const EdgeInsets.all(18),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius:
                      BorderRadius.circular(22),
                ),
                child: Row(
                  children: [

                    Container(
                      width: 55,
                      height: 55,
                      decoration: BoxDecoration(
                        color:
                            const Color(0xFFE3F2FD),
                        borderRadius:
                            BorderRadius.circular(
                          16,
                        ),
                      ),
                      child: const Icon(
                        Icons.history,
                        color:
                            Color(0xFF1565C0),
                        size: 30,
                      ),
                    ),

                    const SizedBox(width: 14),

                    Expanded(
                      child: Column(
                        crossAxisAlignment:
                            CrossAxisAlignment.start,
                        children: [
                          Text(
                            '$totalRecords Records',
                            style:
                                const TextStyle(
                              fontSize: 17,
                              fontWeight:
                                  FontWeight.bold,
                            ),
                          ),
                          const SizedBox(height: 5),
                          Text(
                            'Total Payment: ₹${totalPayment.toStringAsFixed(0)}',
                            style:
                                const TextStyle(
                              color: Colors.grey,
                            ),
                          ),
                        ],
                      ),
                    ),

                    const Icon(
                      Icons.arrow_forward_ios,
                      size: 18,
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),

      bottomNavigationBar:
          NavigationBar(
        selectedIndex: currentIndex,
        onDestinationSelected:
            (index) {
          setState(() {
            currentIndex = index;
          });

          if (index == 0) {
            loadStats();
          }
        },
        destinations: const [
          NavigationDestination(
            icon:
                Icon(Icons.home_outlined),
            selectedIcon:
                Icon(Icons.home),
            label: 'Home',
          ),
          NavigationDestination(
            icon:
                Icon(Icons.history_outlined),
            selectedIcon:
                Icon(Icons.history),
            label: 'History',
          ),
          NavigationDestination(
            icon:
                Icon(Icons.map_outlined),
            selectedIcon:
                Icon(Icons.map),
            label: 'Map',
          ),
          NavigationDestination(
            icon:
                Icon(Icons.person_outline),
            selectedIcon:
                Icon(Icons.person),
            label: 'Profile',
          ),
        ],
      ),
    );
  }
}

// ============================================================
// OPERATION CARD
// ============================================================

class OperationCard extends StatelessWidget {
  final String number;
  final String title;
  final String description;
  final IconData icon;
  final List<Color> colors;
  final VoidCallback onTap;

  const OperationCard({
    super.key,
    required this.number,
    required this.title,
    required this.description,
    required this.icon,
    required this.colors,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return InkWell(
      borderRadius:
          BorderRadius.circular(22),
      onTap: onTap,
      child: Container(
        padding:
            const EdgeInsets.all(18),
        decoration: BoxDecoration(
          gradient:
              LinearGradient(colors: colors),
          borderRadius:
              BorderRadius.circular(22),
        ),
        child: Row(
          children: [

            Container(
              width: 58,
              height: 58,
              decoration: BoxDecoration(
                color:
                    Colors.white.withOpacity(
                  0.20,
                ),
                borderRadius:
                    BorderRadius.circular(17),
              ),
              child: Icon(
                icon,
                color: Colors.white,
                size: 30,
              ),
            ),

            const SizedBox(width: 15),

            Expanded(
              child: Column(
                crossAxisAlignment:
                    CrossAxisAlignment.start,
                children: [
                  Text(
                    number,
                    style:
                        const TextStyle(
                      color: Colors.white70,
                      fontSize: 12,
                    ),
                  ),
                  Text(
                    title,
                    style:
                        const TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontWeight:
                          FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    description,
                    style:
                        const TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                    ),
                  ),
                ],
              ),
            ),

            const CircleAvatar(
              backgroundColor: Colors.white,
              child: Icon(
                Icons.arrow_forward,
                color:
                    Color(0xFF1565C0),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ============================================================
// OP1
// ============================================================

class LandEntryPage extends StatefulWidget {
  const LandEntryPage({super.key});

  @override
  State<LandEntryPage> createState() =>
      _LandEntryPageState();
}

class _LandEntryPageState
    extends State<LandEntryPage> {

  final formKey =
      GlobalKey<FormState>();

  final owner =
      TextEditingController();

  final mobile =
      TextEditingController();

  final village =
      TextEditingController();

  final taluka =
      TextEditingController();

  final survey =
      TextEditingController();

  final length =
      TextEditingController();

  final width =
      TextEditingController();

  final payment =
      TextEditingController();

  DateTime date = DateTime.now();

  double area = 0;

  @override
  void dispose() {
    owner.dispose();
    mobile.dispose();
    village.dispose();
    taluka.dispose();
    survey.dispose();
    length.dispose();
    width.dispose();
    payment.dispose();
    super.dispose();
  }

  void calculateArea() {
    final l =
        double.tryParse(length.text) ?? 0;

    final w =
        double.tryParse(width.text) ?? 0;

    setState(() {
      area = l * w;
    });
  }

  Future<void> chooseDate() async {
    final result =
        await showDatePicker(
      context: context,
      initialDate: date,
      firstDate:
          DateTime(2000),
      lastDate:
          DateTime(2100),
    );

    if (result != null) {
      setState(() {
        date = result;
      });
    }
  }

  Future<void> save() async {
    if (!formKey.currentState!
        .validate()) {
      return;
    }

    calculateArea();

    final record = {
      'owner': owner.text.trim(),
      'mobile': mobile.text.trim(),
      'village': village.text.trim(),
      'taluka': taluka.text.trim(),
      'survey': survey.text.trim(),
      'length': length.text.trim(),
      'width': width.text.trim(),
      'area': area.toStringAsFixed(2),
      'payment': payment.text.trim(),
      'date':
          '${date.day}/${date.month}/${date.year}',
    };

    await HistoryStore.addRecord(
      record,
    );

    if (!mounted) return;

    await showDialog(
      context: context,
      builder: (_) {
        return AlertDialog(
          title: const Text(
            'Save Successful ✅',
          ),
          content: const Text(
            'જમીન માપણીની નોંધ Save થઈ ગઈ છે.\n\nહવે PDF બનાવીને WhatsApp દ્વારા મોકલી શકો છો.',
          ),
          actions: [
            TextButton(
              onPressed: () =>
                  Navigator.pop(context),
              child: const Text('OK'),
            ),
          ],
        );
      },
    );

    if (!mounted) return;

    await showReportOptions(
      record,
    );
  }

  Future<void> showReportOptions(
    Map<String, dynamic> record,
  ) async {
    await showModalBottomSheet(
      context: context,
      builder: (context) {
        return SafeArea(
          child: Padding(
            padding:
                const EdgeInsets.all(20),
            child: Column(
              mainAxisSize:
                  MainAxisSize.min,
              children: [

                const Text(
                  'Land Survey Report',
                  style: TextStyle(
                    fontSize: 20,
                    fontWeight:
                        FontWeight.bold,
                  ),
                ),

                const SizedBox(height: 20),

                ListTile(
                  leading: const Icon(
                    Icons.picture_as_pdf,
                    color: Colors.red,
                  ),
                  title:
                      const Text('PDF બનાવો / Preview'),
                  onTap: () async {
                    Navigator.pop(context);
                    await PdfService
                        .previewPdf(record);
                  },
                ),

                ListTile(
                  leading: const Icon(
                    Icons.share,
                    color: Colors.green,
                  ),
                  title: const Text(
                    'PDF WhatsApp / Share',
                  ),
                  onTap: () async {
                    Navigator.pop(context);
                    await PdfService
                        .sharePdf(record);
                  },
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            const Text('જમીન માપણી નોંધ'),
        backgroundColor:
            const Color(0xFF1565C0),
        foregroundColor: Colors.white,
      ),
      body: Form(
        key: formKey,
        child: ListView(
          padding:
              const EdgeInsets.all(16),
          children: [

            const InfoBox(
              text:
                  'માહિતી Save કર્યા પછી Saved History માં રહેશે અને PDF Report બનાવી શકાશે.',
            ),

            const SizedBox(height: 16),

            AppField(
              controller: owner,
              label: 'માલિકનું નામ',
              icon: Icons.person,
            ),

            AppField(
              controller: mobile,
              label: 'મોબાઇલ નંબર',
              icon: Icons.phone,
              keyboard:
                  TextInputType.phone,
            ),

            AppField(
              controller: village,
              label: 'ગામ',
              icon: Icons.location_city,
            ),

            AppField(
              controller: taluka,
              label: 'તાલુકો',
              icon: Icons.location_on,
            ),

            AppField(
              controller: survey,
              label: 'સર્વે નંબર',
              icon: Icons.numbers,
            ),

            const SizedBox(height: 5),

            InkWell(
              onTap: chooseDate,
              child: InputDecorator(
                decoration:
                    const InputDecoration(
                  labelText:
                      'માપણીની તારીખ',
                  prefixIcon: Icon(
                    Icons.calendar_month,
                  ),
                  border:
                      OutlineInputBorder(),
                ),
                child: Text(
                  '${date.day}/${date.month}/${date.year}',
                ),
              ),
            ),

            const SizedBox(height: 15),

            Row(
              children: [

                Expanded(
                  child: AppField(
                    controller: length,
                    label: 'લંબાઈ (મીટર)',
                    icon:
                        Icons.straighten,
                    keyboard:
                        const TextInputType
                            .numberWithOptions(
                      decimal: true,
                    ),
                    onChanged: (_) =>
                        calculateArea(),
                  ),
                ),

                const SizedBox(width: 10),

                Expanded(
                  child: AppField(
                    controller: width,
                    label: 'પહોળાઈ (મીટર)',
                    icon:
                        Icons.straighten,
                    keyboard:
                        const TextInputType
                            .numberWithOptions(
                      decimal: true,
                    ),
                    onChanged: (_) =>
                        calculateArea(),
                  ),
                ),
              ],
            ),

            Container(
              padding:
                  const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color:
                    const Color(0xFFE3F2FD),
                borderRadius:
                    BorderRadius.circular(16),
              ),
              child: Text(
                'Total Area: ${area.toStringAsFixed(2)} m²',
                style:
                    const TextStyle(
                  fontSize: 17,
                  fontWeight:
                      FontWeight.bold,
                  color:
                      Color(0xFF1565C0),
                ),
              ),
            ),

            const SizedBox(height: 15),

            AppField(
              controller: payment,
              label: 'કુલ પેમેન્ટ (₹)',
              icon:
                  Icons.currency_rupee,
              keyboard:
                  const TextInputType
                      .numberWithOptions(
                decimal: true,
              ),
            ),

            const SizedBox(height: 20),

            SizedBox(
              height: 55,
              child: ElevatedButton.icon(
                onPressed: save,
                icon: const Icon(
                  Icons.save,
                ),
                label: const Text(
                  'Save + PDF Report',
                  style: TextStyle(
                    fontSize: 17,
                    fontWeight:
                        FontWeight.bold,
                  ),
                ),
                style:
                    ElevatedButton.styleFrom(
                  backgroundColor:
                      const Color(
                    0xFF1565C0,
                  ),
                  foregroundColor:
                      Colors.white,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ============================================================
// HISTORY
// ============================================================

class HistoryPage extends StatefulWidget {
  final VoidCallback onHome;

  const HistoryPage({
    super.key,
    required this.onHome,
  });

  @override
  State<HistoryPage> createState() =>
      _HistoryPageState();
}

class _HistoryPageState
    extends State<HistoryPage> {

  List<Map<String, dynamic>> records = [];

  @override
  void initState() {
    super.initState();
    load();
  }

  Future<void> load() async {
    final data =
        await HistoryStore.getRecords();

    if (!mounted) return;

    setState(() {
      records = data.reversed.toList();
    });
  }

  Future<void> delete(
    int displayIndex,
  ) async {
    final originalIndex =
        records.length -
            1 -
            displayIndex;

    await HistoryStore.deleteRecord(
      originalIndex,
    );

    load();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            const Text('Saved History'),
        backgroundColor:
            const Color(0xFF1565C0),
        foregroundColor: Colors.white,
        leading: IconButton(
          icon:
              const Icon(Icons.arrow_back),
          onPressed: widget.onHome,
        ),
      ),
      body: records.isEmpty
          ? const Center(
              child: Text(
                'હજુ કોઈ જમીન માપણી નોંધ નથી.',
                style: TextStyle(
                  fontSize: 18,
                ),
              ),
            )
          : RefreshIndicator(
              onRefresh: load,
              child: ListView.builder(
                padding:
                    const EdgeInsets.all(15),
                itemCount:
                    records.length,
                itemBuilder:
                    (context, index) {
                  final r =
                      records[index];

                  return Card(
                    margin:
                        const EdgeInsets.only(
                      bottom: 12,
                    ),
                    child: Padding(
                      padding:
                          const EdgeInsets.all(
                        15,
                      ),
                      child: Column(
                        children: [

                          Row(
                            children: [

                              const CircleAvatar(
                                backgroundColor:
                                    Color(
                                  0xFFE3F2FD,
                                ),
                                child: Icon(
                                  Icons.landscape,
                                  color:
                                      Color(
                                    0xFF1565C0,
                                  ),
                                ),
                              ),

                              const SizedBox(
                                width: 12,
                              ),

                              Expanded(
                                child: Column(
                                  crossAxisAlignment:
                                      CrossAxisAlignment
                                          .start,
                                  children: [
                                    Text(
                                      r['owner']
                                              ?.toString() ??
                                          '-',
                                      style:
                                          const TextStyle(
                                        fontSize:
                                            17,
                                        fontWeight:
                                            FontWeight
                                                .bold,
                                      ),
                                    ),
                                    Text(
                                      'Survey No: ${r['survey'] ?? '-'}',
                                    ),
                                  ],
                                ),
                              ),

                              IconButton(
                                icon:
                                    const Icon(
                                  Icons
                                      .delete_outline,
                                  color:
                                      Colors.red,
                                ),
                                onPressed: () =>
                                    delete(index),
                              ),
                            ],
                          ),

                          const Divider(),

                          _historyRow(
                            'Location',
                            '${r['village'] ?? '-'}, ${r['taluka'] ?? '-'}',
                          ),

                          _historyRow(
                            'Area',
                            '${r['area'] ?? '0'} m²',
                          ),

                          _historyRow(
                            'Payment',
                            '₹${r['payment'] ?? '0'}',
                          ),

                          _historyRow(
                            'Date',
                            '${r['date'] ?? '-'}',
                          ),

                          const SizedBox(
                            height: 8,
                          ),

                          Row(
                            children: [

                              Expanded(
                                child:
                                    OutlinedButton.icon(
                                  onPressed:
                                      () {
                                    PdfService
                                        .previewPdf(
                                      r,
                                    );
                                  },
                                  icon:
                                      const Icon(
                                    Icons
                                        .picture_as_pdf,
                                  ),
                                  label:
                                      const Text(
                                    'PDF',
                                  ),
                                ),
                              ),

                              const SizedBox(
                                width: 10,
                              ),

                              Expanded(
                                child:
                                    ElevatedButton.icon(
                                  onPressed:
                                      () {
                                    PdfService
                                        .sharePdf(
                                      r,
                                    );
                                  },
                                  icon:
                                      const Icon(
                                    Icons.share,
                                  ),
                                  label:
                                      const Text(
                                    'Share',
                                  ),
                                  style:
                                      ElevatedButton
                                          .styleFrom(
                                    backgroundColor:
                                        Colors
                                            .green,
                                    foregroundColor:
                                        Colors
                                            .white,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ),
    );
  }

  Widget _historyRow(
    String title,
    String value,
  ) {
    return Padding(
      padding:
          const EdgeInsets.only(
        bottom: 7,
      ),
      child: Row(
        children: [
          Text(
            '$title: ',
            style:
                const TextStyle(
              fontWeight:
                  FontWeight.bold,
            ),
          ),
          Expanded(
            child: Text(value),
          ),
        ],
      ),
    );
  }
}

// ============================================================
// AREA CALCULATOR
// ============================================================

class AreaPage extends StatefulWidget {
  const AreaPage({super.key});

  @override
  State<AreaPage> createState() =>
      _AreaPageState();
}

class _AreaPageState
    extends State<AreaPage> {

  final length =
      TextEditingController();

  final width =
      TextEditingController();

  double area = 0;

  void calculate() {
    final l =
        double.tryParse(length.text) ?? 0;

    final w =
        double.tryParse(width.text) ?? 0;

    setState(() {
      area = l * w;
    });
  }

  @override
  void dispose() {
    length.dispose();
    width.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            const Text('Area Calculator'),
        backgroundColor:
            const Color(0xFFEF6C00),
        foregroundColor: Colors.white,
      ),
      body: ListView(
        padding:
            const EdgeInsets.all(16),
        children: [

          AppField(
            controller: length,
            label: 'લંબાઈ (મીટર)',
            icon: Icons.straighten,
            keyboard:
                const TextInputType
                    .numberWithOptions(
              decimal: true,
            ),
          ),

          AppField(
            controller: width,
            label: 'પહોળાઈ (મીટર)',
            icon: Icons.straighten,
            keyboard:
                const TextInputType
                    .numberWithOptions(
              decimal: true,
            ),
          ),

          const SizedBox(height: 10),

          ElevatedButton(
            onPressed: calculate,
            style:
                ElevatedButton.styleFrom(
              backgroundColor:
                  const Color(0xFFEF6C00),
              foregroundColor:
                  Colors.white,
            ),
            child: const Text(
              'Calculate Area',
            ),
          ),

          const SizedBox(height: 25),

          Center(
            child: Text(
              '${area.toStringAsFixed(2)} m²',
              style: const TextStyle(
                fontSize: 32,
                fontWeight:
                    FontWeight.bold,
                color:
                    Color(0xFFEF6C00),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ============================================================
// UNIT
// ============================================================

class UnitPage extends StatefulWidget {
  const UnitPage({super.key});

  @override
  State<UnitPage> createState() =>
      _UnitPageState();
}

class _UnitPageState
    extends State<UnitPage> {

  final input =
      TextEditingController();

  String from = 'Meter';
  String to = 'Feet';
  String result = '0';

  final units = [
    'Meter',
    'Feet',
    'Inch',
    'Yard',
  ];

  double meterValue(
    double value,
    String unit,
  ) {
    if (unit == 'Feet') {
      return value * 0.3048;
    }

    if (unit == 'Inch') {
      return value * 0.0254;
    }

    if (unit == 'Yard') {
      return value * 0.9144;
    }

    return value;
  }

  double convertFromMeter(
    double value,
    String unit,
  ) {
    if (unit == 'Feet') {
      return value / 0.3048;
    }

    if (unit == 'Inch') {
      return value / 0.0254;
    }

    if (unit == 'Yard') {
      return value / 0.9144;
    }

    return value;
  }

  void convert() {
    final value =
        double.tryParse(input.text) ?? 0;

    final meters =
        meterValue(value, from);

    final converted =
        convertFromMeter(
      meters,
      to,
    );

    setState(() {
      result =
          converted.toStringAsFixed(4);
    });
  }

  @override
  void dispose() {
    input.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            const Text('Unit Conversion'),
        backgroundColor:
            const Color(0xFF7B1FA2),
        foregroundColor: Colors.white,
      ),
      body: ListView(
        padding:
            const EdgeInsets.all(16),
        children: [

          AppField(
            controller: input,
            label: 'Value',
            icon: Icons.numbers,
            keyboard:
                const TextInputType
                    .numberWithOptions(
              decimal: true,
            ),
          ),

          DropdownButtonFormField<String>(
            initialValue: from,
            decoration:
                const InputDecoration(
              labelText: 'From',
              border:
                  OutlineInputBorder(),
            ),
            items: units
                .map(
                  (u) => DropdownMenuItem(
                    value: u,
                    child: Text(u),
                  ),
                )
                .toList(),
            onChanged: (v) {
              if (v != null) {
                setState(() {
                  from = v;
                });
              }
            },
          ),

          const SizedBox(height: 12),

          DropdownButtonFormField<String>(
            initialValue: to,
            decoration:
                const InputDecoration(
              labelText: 'To',
              border:
                  OutlineInputBorder(),
            ),
            items: units
                .map(
                  (u) => DropdownMenuItem(
                    value: u,
                    child: Text(u),
                  ),
                )
                .toList(),
            onChanged: (v) {
              if (v != null) {
                setState(() {
                  to = v;
                });
              }
            },
          ),

          const SizedBox(height: 15),

          ElevatedButton(
            onPressed: convert,
            child:
                const Text('Convert'),
          ),

          const SizedBox(height: 20),

          Center(
            child: Text(
              '$result $to',
              style: const TextStyle(
                fontSize: 28,
                fontWeight:
                    FontWeight.bold,
                color:
                    Color(0xFF7B1FA2),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ============================================================
// GPS
// ============================================================

class GpsPage extends StatelessWidget {
  const GpsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            const Text('GPS Survey'),
        backgroundColor:
            const Color(0xFF00897B),
        foregroundColor:
            Colors.white,
      ),
      body: Center(
        child: Padding(
          padding:
              const EdgeInsets.all(25),
          child: Column(
            mainAxisAlignment:
                MainAxisAlignment.center,
            children: [

              const Icon(
                Icons.gps_fixed,
                size: 80,
                color:
                    Color(0xFF00897B),
              ),

              const SizedBox(height: 15),

              const Text(
                'GPS Survey',
                style: TextStyle(
                  fontSize: 24,
                  fontWeight:
                      FontWeight.bold,
                ),
              ),

              const SizedBox(height: 10),

              const Text(
                'GPS boundary અને live location module આગળ connect કરી શકાય છે.',
                textAlign:
                    TextAlign.center,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ============================================================
// MAP
// ============================================================

class MapPage extends StatelessWidget {
  final VoidCallback onHome;

  const MapPage({
    super.key,
    required this.onHome,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Map'),
        backgroundColor:
            const Color(0xFF1565C0),
        foregroundColor:
            Colors.white,
        leading: IconButton(
          icon:
              const Icon(Icons.arrow_back),
          onPressed: onHome,
        ),
      ),
      body: const Center(
        child: Text(
          'Survey Map Module',
          style: TextStyle(
            fontSize: 24,
            fontWeight:
                FontWeight.bold,
          ),
        ),
      ),
    );
  }
}

// ============================================================
// PROFILE
// ============================================================

class ProfilePage extends StatelessWidget {
  final VoidCallback onHome;

  const ProfilePage({
    super.key,
    required this.onHome,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            const Text('Profile'),
        backgroundColor:
            const Color(0xFF1565C0),
        foregroundColor:
            Colors.white,
        leading: IconButton(
          icon:
              const Icon(Icons.arrow_back),
          onPressed: onHome,
        ),
      ),
      body: ListView(
        padding:
            const EdgeInsets.all(20),
        children: [

          Center(
            child: Image.asset(
              'assets/rudra_logo.jpg',
              width: 120,
              height: 120,
            ),
          ),

          const SizedBox(height: 15),

          const Center(
            child: Text(
              'RUDRA SURVEYOR',
              style: TextStyle(
                fontSize: 25,
                fontWeight:
                    FontWeight.bold,
                color:
                    Color(0xFF123B68),
              ),
            ),
          ),

          const SizedBox(height: 25),

          const ListTile(
            leading:
                Icon(Icons.support_agent),
            title:
                Text('Customer Care'),
            subtitle:
                Text('8487847474'),
          ),

          const ListTile(
            leading:
                Icon(Icons.person),
            title:
                Text('Customer Care Name'),
            subtitle:
                Text('Y.M. DHUNDHALAVA'),
          ),
        ],
      ),
    );
  }
}

// ============================================================
// SETTINGS
// ============================================================

class SettingsPage extends StatelessWidget {
  const SettingsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            const Text('Settings'),
        backgroundColor:
            const Color(0xFF1565C0),
        foregroundColor:
            Colors.white,
      ),
      body: const ListView(
        children: [

          ListTile(
            leading:
                Icon(Icons.language),
            title:
                Text('Language'),
            subtitle:
                Text('ગુજરાતી / English'),
          ),

          ListTile(
            leading:
                Icon(Icons.info_outline),
            title:
                Text('About RUDRA SURVEYOR'),
            subtitle:
                Text(
                  'Professional Land Surveyor App',
                ),
          ),
        ],
      ),
    );
  }
}

// ============================================================
// FIELD
// ============================================================

class AppField extends StatelessWidget {
  final TextEditingController controller;
  final String label;
  final IconData icon;
  final TextInputType? keyboard;
  final ValueChanged<String>? onChanged;

  const AppField({
    super.key,
    required this.controller,
    required this.label,
    required this.icon,
    this.keyboard,
    this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding:
          const EdgeInsets.only(
        bottom: 14,
      ),
      child: TextFormField(
        controller: controller,
        keyboardType: keyboard,
        onChanged: onChanged,
        validator: (value) {
          if (value == null ||
              value.trim().isEmpty) {
            return '$label લખો';
          }
          return null;
        },
        decoration:
            InputDecoration(
          labelText: label,
          prefixIcon:
              Icon(icon),
          border:
              OutlineInputBorder(
            borderRadius:
                BorderRadius.circular(
              14,
            ),
          ),
          filled: true,
          fillColor:
              Colors.white,
        ),
      ),
    );
  }
}

// ============================================================
// INFO BOX
// ============================================================

class InfoBox extends StatelessWidget {
  final String text;

  const InfoBox({
    super.key,
    required this.text,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding:
          const EdgeInsets.all(15),
      decoration: BoxDecoration(
        color:
            const Color(0xFFE3F2FD),
        borderRadius:
            BorderRadius.circular(16),
      ),
      child: Row(
        children: [
          const Icon(
            Icons.info_outline,
            color:
                Color(0xFF1565C0),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Text(text),
          ),
        ],
      ),
    );
  }
}
